import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.List;


public class MainInventory {

    private JPanel inventoryPanel;
    private JScrollPane inventoryScroll;
    private JTextArea inventoryDisplay;
    private JLabel inventoryLabel;
    private JFrame i;

    MainInventory(Player p) {
        inventoryDisplay.setEditable(false);
        inventoryLabel.setText(p.getName() + "'s Inventory");

        p.addToInventory(new Item("Helmet", "Head Protection", 3));
        p.addToInventory(new Item("Sword", "Stabby stick", 2));

        List<Item> inventory = p.getInventory();

        for (Item i : inventory) {
            inventoryDisplay.setText(inventoryDisplay.getText() + i.getName() + "\n");
        }
    }

    public void createFrame() {
        i = new JFrame("Inventory");
        i.setContentPane(inventoryPanel);
        i.pack();
        i.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        i.setVisible(false);
    }

    public void setVisible() {
        i.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        inventoryPanel = new JPanel();
        inventoryPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        inventoryScroll = new JScrollPane();
        inventoryPanel.add(inventoryScroll, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 300), null, 0, false));
        inventoryDisplay = new JTextArea();
        inventoryScroll.setViewportView(inventoryDisplay);
        inventoryLabel = new JLabel();
        inventoryLabel.setText("Player's Inventory");
        inventoryPanel.add(inventoryLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return inventoryPanel;
    }

}
