import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;

/**
 * The class that will begin every run of the program.
 * This class is called to display the Start Menu of the game.
 * It will lead into every other UI, depending on user choice of
 * button.
 *
 * @version 1.0
 * @since 6.3.2023
 * @author Elijah Johnson
 */
public class MainStartMenu {
    private JPanel startMenuPanel;
    private JButton continueButton;
    private JButton newGameButton;
    private JLabel titleLabel;
    private JButton exitButton;
    private static JFrame s;
    /**
     * The constructor for the MainStartMenu. This has all UI functionality.
     */
    MainStartMenu() {
        newGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MainNewGame newGame = new MainNewGame();
                newGame.createFrame();
                s.dispose();
            }
        });
        continueButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                //connect to the database
                Connection con = DBConnector.connect();
                //pull from database
                GameMap map = null;
                try {
                    map = DBConnector.getLatestSaveState(con);
                } catch (SQLException ex) {
                    throw new RuntimeException(ex);
                }
                //get player
                Player player = map.getPlayer();
                //create main
                Main main = new Main(player, map, con);
                main.startGame();
                s.dispose();
            }
        });
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
    }
    /**
     * A method to be called in Main that creates and displays the start menu UI.
     */
    void createFrame() {
        s = new JFrame("The BEB Game");
        s.setContentPane(new MainStartMenu().startMenuPanel);
        s.pack();
        s.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        s.setVisible(true);
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        startMenuPanel = new JPanel();
        startMenuPanel.setLayout(new GridLayoutManager(7, 1, new Insets(40, 20, 40, 20), -1, -1));
        continueButton = new JButton();
        continueButton.setText("Continue");
        startMenuPanel.add(continueButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 10), null, 0, false));
        newGameButton = new JButton();
        newGameButton.setText("New Game");
        startMenuPanel.add(newGameButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 10), null, 0, false));
        exitButton = new JButton();
        exitButton.setText("Exit Game");
        startMenuPanel.add(exitButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 10), null, 0, false));
        final Spacer spacer1 = new Spacer();
        startMenuPanel.add(spacer1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        final Spacer spacer2 = new Spacer();
        startMenuPanel.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        titleLabel = new JLabel();
        titleLabel.setText("THE BEB GAME");
        startMenuPanel.add(titleLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        startMenuPanel.add(spacer3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return startMenuPanel;
    }
}
