import javax.swing.*;
import java.awt.*;

public class MainQuests {
    private JPanel questsPanel;
    private JLabel testLabel;

    MainQuests() {
    }

    public void createFrame() {
        JFrame q = new JFrame("Quests");
        q.setContentPane(new MainQuests().questsPanel);
        q.pack();
        q.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        q.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        questsPanel = new JPanel();
        questsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(100, 100, 100, 100), -1, -1));
        testLabel = new JLabel();
        testLabel.setText("Success");
        questsPanel.add(testLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return questsPanel;
    }
}
